# hugo.toml

baseurl = "https://jmkeyes.ca/"
theme = "black-and-light"

title = "J. M. Keyes"
author = "Joshua M. Keyes"

canonifyurls = true
languagecode = "en"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "J. M. Keyes"
  disableWebFonts = false

[services]
  [services.googleAnalytics]
    id = 'G-BWYQ858RMF'

[[menu.main]]
  name = "About"
  url  = "https://jmkeyes.ca/#about"
[[menu.main]]
  name = "Projects"
  url  = "https://github.com/jmkeyes/"
[[menu.main]]
  name = "Contact"
  url  = "https://jmkeyes.ca/#contact"
